name: Continuous Integration
# 
on:
   workflow_run:
    workflows: [LintGulp]
    types:
      - completed

jobs:
  merge-me:
    name: Merge me!
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_REMOVE_LABELS: "automerge"
    # Only allow automerging from staging into master
    if: github.event.workflow_run.pull_requests[0].base.ref == 'master' && github.event.workflow_run.pull_requests[0].head.ref == 'staging'
