name: Check Code Style

on:
  pull_request:
    branches: ['staging', 'master']

jobs:
  phplint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: stoicbuddha/PHP-Lint@master