name: Fix Code Style

on:
  pull_request:
    branches: ['staging']

jobs:
  phplint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: stoicbuddha/PHP-Lint@master