name: Fix Code Style

on:
  pull_request:
    branches: ['staging']

jobs:
  laravel-pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Composer Install
        run: composer install

      - name: Run Laravel Pint
        run: ./vendor/bin/pint